- group:
    name: app
    state: present
    system: yes

- name: Creating user app1
  user:
    name: app1
    state: present
    shell: /bin/bash
    home: /opt/app1
    groups: app

- name: Creating user app2
  user:
    name: app2
    state: present
    shell: /bin/bash
    home: /opt/app2
    groups: app

- name: Installing Basic Software
  apt: pkg={{ item  }} state=installed
  with_items:
   - docker.io
