- group:
    name: app
    state: present
    system: yes

- name: Creating users
  user:
    name: "{{ item }}"
    state: present
    shell: /bin/bash
    home: "/opt/{{ item }}"
    groups: app
  with_items:
   - app1
   - app2
   
- name: Installing Basic Software
  apt: pkg={{ item  }} state=installed
  with_items:
   - docker.io
